import {
  AdminUser,
  User,
  Calculation,
  AISolution,
  ScanRecord,
  SolutionReport,
  ThemeItem,
  NotificationItem,
  AuditLog,
  FeatureFlag,
  SystemHealthItem,
  AIProviderConfig,
} from "../types";

export const INITIAL_ADMINS: AdminUser[] = [
  {
    id: "adm-1",
    name: "Sarah Jenkins (Super Admin)",
    email: "sarah.admin@solvecalc.com",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    twoFactorEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    createdAt: "2026-01-10T08:00:00.000Z",
  },
  {
    id: "adm-2",
    name: "Alex Rivera",
    email: "alex.r@solvecalc.com",
    role: "ADMIN",
    status: "ACTIVE",
    twoFactorEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdAt: "2026-02-15T09:30:00.000Z",
  },
  {
    id: "adm-3",
    name: "Mia Chen (Moderator)",
    email: "mia.mod@solvecalc.com",
    role: "MODERATOR",
    status: "ACTIVE",
    twoFactorEnabled: false,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    createdAt: "2026-03-01T11:00:00.000Z",
  },
  {
    id: "adm-4",
    name: "Sam Wilson (Support)",
    email: "sam.support@solvecalc.com",
    role: "SUPPORT",
    status: "ACTIVE",
    twoFactorEnabled: false,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdAt: "2026-03-12T14:20:00.000Z",
  },
  {
    id: "adm-5",
    name: "Andy Taylor (Data Analyst)",
    email: "andy.analyst@solvecalc.com",
    role: "ANALYST",
    status: "ACTIVE",
    twoFactorEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
    createdAt: "2026-04-01T10:15:00.000Z",
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "usr-101",
    name: "David Kim",
    email: "david.kim@university.edu",
    status: "ACTIVE",
    accountType: "PRO_LIFETIME",
    calculationsCount: 342,
    aiSolvesCount: 88,
    scansCount: 45,
    registeredAt: "2026-02-01T10:00:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    devicePlatform: "iOS",
    appVersion: "1.0.4",
  },
  {
    id: "usr-102",
    name: "Elena Rostova",
    email: "elena.r@gmail.com",
    status: "ACTIVE",
    accountType: "FREE",
    calculationsCount: 156,
    aiSolvesCount: 24,
    scansCount: 18,
    registeredAt: "2026-03-15T14:20:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    devicePlatform: "Android",
    appVersion: "1.0.4",
  },
  {
    id: "usr-103",
    name: "Marcus Vance",
    email: "marcus.v@outlook.com",
    status: "ACTIVE",
    accountType: "PRO_LIFETIME",
    calculationsCount: 890,
    aiSolvesCount: 215,
    scansCount: 130,
    registeredAt: "2026-01-20T09:12:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    devicePlatform: "Android",
    appVersion: "1.0.4",
  },
  {
    id: "usr-104",
    name: "Sophia Martinez",
    email: "smartinez99@yahoo.com",
    status: "ACTIVE",
    accountType: "FREE",
    calculationsCount: 78,
    aiSolvesCount: 12,
    scansCount: 9,
    registeredAt: "2026-04-10T11:45:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    devicePlatform: "iOS",
    appVersion: "1.0.3",
  },
  {
    id: "usr-105",
    name: "Bad Actor (Spammer)",
    email: "bot_spammer_99@tempmail.org",
    status: "BANNED",
    accountType: "FREE",
    calculationsCount: 2,
    aiSolvesCount: 0,
    scansCount: 0,
    registeredAt: "2026-05-01T02:10:00.000Z",
    lastActiveAt: "2026-05-01T02:15:00.000Z",
    devicePlatform: "Android",
    appVersion: "1.0.1",
  },
  {
    id: "usr-106",
    name: "Lucas Scott",
    email: "lucas.s@mathdept.org",
    status: "ACTIVE",
    accountType: "PRO_LIFETIME",
    calculationsCount: 1240,
    aiSolvesCount: 310,
    scansCount: 195,
    registeredAt: "2026-01-05T08:30:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    devicePlatform: "iOS",
    appVersion: "1.0.4",
  },
  {
    id: "usr-107",
    name: "Chloe Bennett",
    email: "chloe.b@highschool.edu",
    status: "SUSPENDED",
    accountType: "FREE",
    calculationsCount: 45,
    aiSolvesCount: 8,
    scansCount: 5,
    registeredAt: "2026-04-22T16:00:00.000Z",
    lastActiveAt: "2026-05-10T12:00:00.000Z",
    devicePlatform: "Android",
    appVersion: "1.0.2",
  },
  {
    id: "usr-108",
    name: "Nathan Drake",
    email: "nathan.d@adventures.com",
    status: "ACTIVE",
    accountType: "PRO_LIFETIME",
    calculationsCount: 520,
    aiSolvesCount: 142,
    scansCount: 84,
    registeredAt: "2026-02-28T13:10:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    devicePlatform: "iOS",
    appVersion: "1.0.4",
  },
];

export const INITIAL_CALCULATIONS: Calculation[] = [
  {
    id: "calc-1",
    userId: "usr-101",
    userName: "David Kim",
    expression: "sin(30) + cos(60)",
    result: "1",
    mode: "scientific",
    angleMode: "DEG",
    isError: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: "calc-2",
    userId: "usr-103",
    userName: "Marcus Vance",
    expression: "2^10 * sqrt(144)",
    result: "12288",
    mode: "scientific",
    angleMode: "DEG",
    isError: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: "calc-3",
    userId: "usr-102",
    userName: "Elena Rostova",
    expression: "1500 * 15% + 45",
    result: "270",
    mode: "basic",
    angleMode: "DEG",
    isError: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
  },
  {
    id: "calc-4",
    userId: "usr-106",
    userName: "Lucas Scott",
    expression: "ln(e^5) - log(1000)",
    result: "2",
    mode: "scientific",
    angleMode: "RAD",
    isError: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: "calc-5",
    userId: "usr-104",
    userName: "Sophia Martinez",
    expression: "100 / 0",
    result: "Error: Division by zero",
    mode: "basic",
    angleMode: "DEG",
    isError: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
  },
];

export const INITIAL_AI_SOLUTIONS: AISolution[] = [
  {
    id: "sol-901",
    userId: "usr-101",
    userName: "David Kim",
    question: "2x + 5 = 15",
    questionType: "Linear Equation",
    finalAnswer: "x = 5",
    solverType: "Groq Llama-3.3 + Deterministic Verifier",
    provider: "Groq Cloud",
    model: "llama-3.3-70b-versatile",
    tokensUsed: 142,
    latencyMs: 380,
    verificationStatus: "VERIFIED",
    status: "COMPLETED",
    steps: [
      {
        stepNumber: 1,
        title: "Subtract 5 from both sides",
        explanation: "2x + 5 - 5 = 15 - 5",
        whyExplanation: "Isolate the variable term on the left side of the equation.",
        equation: "2x = 10",
      },
      {
        stepNumber: 2,
        title: "Divide both sides by 2",
        explanation: "2x / 2 = 10 / 2",
        whyExplanation: "Divide by the coefficient of x to find the unit value of x.",
        equation: "x = 5",
      },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: "sol-902",
    userId: "usr-103",
    userName: "Marcus Vance",
    question: "x^2 + 5x + 6 = 0",
    questionType: "Quadratic Equation",
    finalAnswer: "x = -2, x = -3",
    solverType: "Groq Llama-3.3 + Deterministic Verifier",
    provider: "Groq Cloud",
    model: "llama-3.3-70b-versatile",
    tokensUsed: 260,
    latencyMs: 440,
    verificationStatus: "VERIFIED",
    status: "COMPLETED",
    steps: [
      {
        stepNumber: 1,
        title: "Calculate Discriminant Δ = b² - 4ac",
        explanation: "Δ = 5² - 4(1)(6) = 25 - 24 = 1",
        whyExplanation: "Since Δ > 0, the equation has two distinct real roots.",
        equation: "Δ = 1",
      },
      {
        stepNumber: 2,
        title: "Apply Quadratic Formula x = (-b ± √Δ) / 2a",
        explanation: "x = (-5 ± √1) / 2 = (-5 ± 1) / 2",
        whyExplanation: "Evaluate both addition and subtraction branches.",
        equation: "x₁ = -2, x₂ = -3",
      },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: "sol-903",
    userId: "usr-106",
    userName: "Lucas Scott",
    question: "∫ (3x² + 2x - 5) dx",
    questionType: "Indefinite Integral",
    finalAnswer: "x³ + x² - 5x + C",
    solverType: "Groq Llama-3.3 + Verifier",
    provider: "Groq Cloud",
    model: "llama-3.3-70b-versatile",
    tokensUsed: 195,
    latencyMs: 510,
    verificationStatus: "VERIFIED",
    status: "COMPLETED",
    steps: [
      {
        stepNumber: 1,
        title: "Integrate each term individually using Power Rule",
        explanation: "∫ 3x² dx = x³, ∫ 2x dx = x², ∫ -5 dx = -5x",
        whyExplanation: "Power rule states ∫ xⁿ dx = xⁿ⁺¹ / (n+1).",
        equation: "F(x) = x³ + x² - 5x + C",
      },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
];

export const INITIAL_SCANS: ScanRecord[] = [
  {
    id: "scn-501",
    userId: "usr-101",
    userName: "David Kim",
    rawOcrText: "2x + 5 = 15",
    finalQuestion: "2x + 5 = 15",
    status: "SUCCESS",
    confidence: 0.99,
    latencyMs: 650,
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "scn-502",
    userId: "usr-102",
    userName: "Elena Rostova",
    rawOcrText: "3x + 9 = 1S",
    correctedText: "3x + 9 = 18",
    finalQuestion: "3x + 9 = 18",
    status: "MANUALLY_CORRECTED",
    confidence: 0.81,
    latencyMs: 720,
    timestamp: new Date(Date.now() - 1000 * 60 * 48).toISOString(),
  },
  {
    id: "scn-503",
    userId: "usr-104",
    userName: "Sophia Martinez",
    rawOcrText: "Blurry image text unreadable",
    finalQuestion: "Unresolved",
    status: "FAILED",
    confidence: 0.22,
    latencyMs: 410,
    timestamp: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
  },
];

export const INITIAL_REPORTS: SolutionReport[] = [
  {
    id: "rep-001",
    solutionId: "sol-902",
    userId: "usr-104",
    userName: "Sophia Martinez",
    question: "x^2 + 5x + 6 = 0",
    answer: "x = -2, x = -3",
    reason: "CONFUSING_EXPLANATION",
    userComment: "The discriminant formula explanation was a bit fast for beginner algebra.",
    status: "PENDING",
    createdAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
  },
  {
    id: "rep-002",
    solutionId: "sol-old-44",
    userId: "usr-102",
    userName: "Elena Rostova",
    question: "sin(90) in RAD vs DEG",
    answer: "0.89399666",
    reason: "INCORRECT_ANSWER",
    userComment: "User expected DEG answer (1) but mode was set to RAD without clear indication.",
    status: "RESOLVED",
    createdAt: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
  },
];

export const INITIAL_THEMES: ThemeItem[] = [
  {
    id: "white",
    name: "Pure White",
    description: "Crisp, minimalist pure white aesthetic with dark slate typography.",
    primaryColor: "#0F172A",
    secondaryColor: "#F1F5F9",
    backgroundColor: "#FFFFFF",
    surfaceColor: "#F8FAFC",
    numberButtonColor: "#F1F5F9",
    operatorButtonColor: "#E2E8F0",
    isDark: false,
    isActive: true,
    isDefault: false,
    isPremium: false,
    order: 1,
  },
  {
    id: "casio",
    name: "Casio Scientific",
    description: "Iconic classic Casio fx-991EX retro calculator casing with greenish LCD.",
    primaryColor: "#38BDF8",
    secondaryColor: "#262C36",
    backgroundColor: "#1E222A",
    surfaceColor: "#8FA486",
    numberButtonColor: "#ECEFF1",
    operatorButtonColor: "#333A42",
    isDark: true,
    isActive: true,
    isDefault: false,
    isPremium: false,
    order: 2,
  },
  {
    id: "midnight",
    name: "Midnight Blue",
    description: "Deep modern navy blue with sapphire blue accents.",
    primaryColor: "#3B82F6",
    secondaryColor: "#1E293B",
    backgroundColor: "#0F172A",
    surfaceColor: "#1E293B",
    numberButtonColor: "#1E293B",
    operatorButtonColor: "#334155",
    isDark: true,
    isActive: true,
    isDefault: true,
    isPremium: false,
    order: 3,
  },
  {
    id: "classic",
    name: "Classic Dark",
    description: "High-contrast OLED black with classic orange arithmetic operators.",
    primaryColor: "#FF9500",
    secondaryColor: "#2C2C2E",
    backgroundColor: "#000000",
    surfaceColor: "#1C1C1E",
    numberButtonColor: "#2C2C2E",
    operatorButtonColor: "#FF9500",
    isDark: true,
    isActive: true,
    isDefault: false,
    isPremium: false,
    order: 4,
  },
  {
    id: "ocean",
    name: "Ocean Cyan",
    description: "Refreshing marine cyan palette for clear visual contrast.",
    primaryColor: "#06B6D4",
    secondaryColor: "#164E63",
    backgroundColor: "#082F49",
    surfaceColor: "#0C4A6E",
    numberButtonColor: "#0E7490",
    operatorButtonColor: "#155E75",
    isDark: true,
    isActive: true,
    isDefault: false,
    isPremium: true,
    order: 5,
  },
  {
    id: "forest",
    name: "Emerald Forest",
    description: "Soothing natural emerald green palette for long study sessions.",
    primaryColor: "#10B981",
    secondaryColor: "#064E3B",
    backgroundColor: "#022C22",
    surfaceColor: "#064E3B",
    numberButtonColor: "#047857",
    operatorButtonColor: "#065F46",
    isDark: true,
    isActive: true,
    isDefault: false,
    isPremium: true,
    order: 6,
  },
  {
    id: "purple",
    name: "Cyber Purple",
    description: "Futuristic neon purple palette with deep violet contrast.",
    primaryColor: "#8B5CF6",
    secondaryColor: "#2E1065",
    backgroundColor: "#1E1035",
    surfaceColor: "#3B1873",
    numberButtonColor: "#4C1D95",
    operatorButtonColor: "#5B21B6",
    isDark: true,
    isActive: true,
    isDefault: false,
    isPremium: true,
    order: 7,
  },
  {
    id: "sunset",
    name: "Sunset Orange",
    description: "Warm gradient sunset tones for energetic problem solving.",
    primaryColor: "#F97316",
    secondaryColor: "#7C2D12",
    backgroundColor: "#431407",
    surfaceColor: "#7C2D12",
    numberButtonColor: "#9A3412",
    operatorButtonColor: "#C2410C",
    isDark: true,
    isActive: true,
    isDefault: false,
    isPremium: true,
    order: 8,
  },
  {
    id: "minimal",
    name: "Minimal Light",
    description: "Soft gray daylight theme with clear indigo action buttons.",
    primaryColor: "#2563EB",
    secondaryColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    surfaceColor: "#FFFFFF",
    numberButtonColor: "#F1F5F9",
    operatorButtonColor: "#E2E8F0",
    isDark: false,
    isActive: true,
    isDefault: false,
    isPremium: false,
    order: 9,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "✨ New Themes: Pure White & Casio Scientific!",
    message: "Check out the two new themes in Settings to customize your SolveCalc experience.",
    type: "FEATURE",
    targetAudience: "ALL",
    status: "SENT",
    sentAt: "2026-05-01T12:00:00.000Z",
    deliveredCount: 1420,
    openedCount: 980,
  },
  {
    id: "notif-2",
    title: "⚡ Groq AI Mathematical Snapping is Live",
    message: "Snap any textbook question with your camera for ultra-fast step-by-step explanations.",
    type: "SYSTEM",
    targetAudience: "ALL",
    status: "SENT",
    sentAt: "2026-04-15T09:30:00.000Z",
    deliveredCount: 1250,
    openedCount: 1105,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud-001",
    adminId: "adm-1",
    adminName: "Sarah Jenkins",
    adminRole: "SUPER_ADMIN",
    action: "UPDATE_AI_PROVIDER",
    resource: "AIProviderConfig",
    resourceId: "groq-primary",
    details: "Set Groq Cloud (Llama 3.3) as primary mathematical AI provider with 15s timeout.",
    ipAddress: "192.168.1.45",
    status: "SUCCESS",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "aud-002",
    adminId: "adm-2",
    adminName: "Alex Rivera",
    adminRole: "ADMIN",
    action: "CREATE_THEME",
    resource: "ThemeItem",
    resourceId: "casio",
    details: "Created 'Casio Scientific' retro theme preset with LCD matrix styling.",
    ipAddress: "192.168.1.112",
    status: "SUCCESS",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: "aud-003",
    adminId: "adm-3",
    adminName: "Mia Chen",
    adminRole: "MODERATOR",
    action: "RESOLVE_SOLUTION_REPORT",
    resource: "SolutionReport",
    resourceId: "rep-002",
    details: "Resolved user report on angle mode ambiguity for trig functions.",
    ipAddress: "192.168.1.88",
    status: "SUCCESS",
    timestamp: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
  },
  {
    id: "aud-004",
    adminId: "adm-1",
    adminName: "Sarah Jenkins",
    adminRole: "SUPER_ADMIN",
    action: "SUSPEND_USER",
    resource: "User",
    resourceId: "usr-105",
    details: "Banned spam bot account 'bot_spammer_99@tempmail.org'.",
    ipAddress: "192.168.1.45",
    status: "SUCCESS",
    timestamp: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
  },
];

export const INITIAL_AI_PROVIDERS: AIProviderConfig[] = [
  {
    id: "groq-primary",
    name: "Groq Cloud (Ultra-Fast)",
    providerType: "GROQ",
    isPrimary: true,
    isFallback: false,
    isEnabled: true,
    apiKeyMasked: "gsk_••••••••••••••••••••••••••••••••",
    model: "llama-3.3-70b-versatile",
    timeoutMs: 12000,
    maxTokens: 2048,
    dailyLimitUsd: 50.0,
    monthlyLimitUsd: 1200.0,
    currentDaySpendUsd: 4.85,
    currentMonthSpendUsd: 142.3,
  },
  {
    id: "gemini-fallback",
    name: "Google Gemini Cloud",
    providerType: "GEMINI",
    isPrimary: false,
    isFallback: true,
    isEnabled: true,
    apiKeyMasked: "AIzaSy••••••••••••••••••••••••••••",
    model: "gemini-1.5-pro",
    timeoutMs: 15000,
    maxTokens: 4096,
    dailyLimitUsd: 100.0,
    monthlyLimitUsd: 2500.0,
    currentDaySpendUsd: 0.92,
    currentMonthSpendUsd: 38.6,
  },
  {
    id: "local-deterministic",
    name: "Offline Deterministic Engine",
    providerType: "LOCAL_DETERMINISTIC",
    isPrimary: false,
    isFallback: false,
    isEnabled: true,
    apiKeyMasked: "N/A (Built-in)",
    model: "SolveCalc AST Analytical Solver",
    timeoutMs: 500,
    maxTokens: 0,
    dailyLimitUsd: 0,
    monthlyLimitUsd: 0,
    currentDaySpendUsd: 0,
    currentMonthSpendUsd: 0,
  },
];

export const INITIAL_FEATURE_FLAGS: FeatureFlag[] = [
  {
    id: "feat-1",
    key: "AI_SOLVER_ENABLED",
    name: "AI Step-by-Step Solver",
    description: "Enable AI mathematical solving and Learn Mode explanations.",
    isEnabled: true,
    category: "AI",
  },
  {
    id: "feat-2",
    key: "CAMERA_OCR_ENABLED",
    name: "Camera Math Scanner (OCR)",
    description: "Enable photo equation capture and vision recognition.",
    isEnabled: true,
    category: "SCANNER",
  },
  {
    id: "feat-3",
    key: "PRO_LIFETIME_TIER",
    name: "Pro Lifetime Tier ($10 USD)",
    description: "Enable one-time $10 USD lifetime purchase and ad removal.",
    isEnabled: true,
    category: "MONETIZATION",
  },
  {
    id: "feat-4",
    key: "APP_OPEN_ADS",
    name: "App-Open Full Screen Ads",
    description: "Show 3-second skippable app open ad for free-tier users.",
    isEnabled: true,
    category: "MONETIZATION",
  },
  {
    id: "feat-5",
    key: "TOP_BANNER_ADS",
    name: "Top In-App Banner Ads",
    description: "Display small top banner ad during active calculator usage.",
    isEnabled: true,
    category: "MONETIZATION",
  },
  {
    id: "feat-6",
    key: "CUSTOM_THEMES_ENGINE",
    name: "Custom Theme Creator",
    description: "Allow users to customize and build their own color palettes.",
    isEnabled: true,
    category: "CORE",
  },
];

export const INITIAL_SYSTEM_HEALTH: SystemHealthItem[] = [
  {
    name: "SolveCalc Core API",
    status: "ONLINE",
    latencyMs: 124,
    message: "Operating normally (99.98% uptime)",
    lastChecked: "Just now",
  },
  {
    name: "Groq AI Provider",
    status: "ONLINE",
    latencyMs: 380,
    message: "Llama-3.3-70b latency average 380ms",
    lastChecked: "Just now",
  },
  {
    name: "PostgreSQL Database",
    status: "ONLINE",
    latencyMs: 28,
    message: "Connection pool healthy (4/20 active connections)",
    lastChecked: "Just now",
  },
  {
    name: "Redis Cache & Rate Limiter",
    status: "ONLINE",
    latencyMs: 8,
    message: "Memory utilization 14.2%",
    lastChecked: "Just now",
  },
  {
    name: "OCR Vision Engine",
    status: "ONLINE",
    latencyMs: 650,
    message: "Vision recognition success rate 96.4%",
    lastChecked: "Just now",
  },
  {
    name: "Push Notification Service",
    status: "ONLINE",
    latencyMs: 95,
    message: "APNs & FCM delivery pipelines active",
    lastChecked: "Just now",
  },
];
