import {
  AdminUser,
  User,
  Calculation,
  AISolution,
  ScanRecord,
  SolutionReport,
  ThemeItem,
  NotificationItem,
  AuditLog,
  FeatureFlag,
  SystemHealthItem,
  AIProviderConfig,
  PremiumPurchase,
  AdNetworkItem,
  HouseAdCampaign,
  RemoteConfigVersion,
  MonetizationAlert,
} from "../types";

export const INITIAL_ADMINS: AdminUser[] = [
  {
    id: "adm-1",
    name: "Sarah Jenkins (Super Admin)",
    email: "sarah.admin@solvecalc.com",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    twoFactorEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    createdAt: "2026-01-10T08:00:00.000Z",
  },
  {
    id: "adm-2",
    name: "Alex Rivera",
    email: "alex.r@solvecalc.com",
    role: "ADMIN",
    status: "ACTIVE",
    twoFactorEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdAt: "2026-02-15T09:30:00.000Z",
  },
  {
    id: "adm-3",
    name: "Mia Chen (Moderator)",
    email: "mia.mod@solvecalc.com",
    role: "MODERATOR",
    status: "ACTIVE",
    twoFactorEnabled: false,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    createdAt: "2026-03-01T11:00:00.000Z",
  },
  {
    id: "adm-4",
    name: "Sam Wilson (Support)",
    email: "sam.support@solvecalc.com",
    role: "SUPPORT",
    status: "ACTIVE",
    twoFactorEnabled: false,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdAt: "2026-03-12T14:20:00.000Z",
  },
  {
    id: "adm-5",
    name: "Andy Taylor (Data Analyst)",
    email: "andy.analyst@solvecalc.com",
    role: "ANALYST",
    status: "ACTIVE",
    twoFactorEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
    createdAt: "2026-04-01T10:15:00.000Z",
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "usr-101",
    name: "David Kim",
    email: "david.kim@university.edu",
    status: "ACTIVE",
    accountType: "PRO_LIFETIME",
    calculationsCount: 342,
    aiSolvesCount: 88,
    scansCount: 45,
    registeredAt: "2026-02-01T10:00:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    devicePlatform: "iOS",
    appVersion: "1.0.4",
  },
  {
    id: "usr-102",
    name: "Elena Rostova",
    email: "elena.r@gmail.com",
    status: "ACTIVE",
    accountType: "FREE",
    calculationsCount: 156,
    aiSolvesCount: 24,
    scansCount: 18,
    registeredAt: "2026-03-15T14:20:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    devicePlatform: "Android",
    appVersion: "1.0.4",
  },
  {
    id: "usr-103",
    name: "Marcus Vance",
    email: "marcus.v@outlook.com",
    status: "ACTIVE",
    accountType: "PRO_LIFETIME",
    calculationsCount: 890,
    aiSolvesCount: 215,
    scansCount: 130,
    registeredAt: "2026-01-20T09:12:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    devicePlatform: "Android",
    appVersion: "1.0.4",
  },
  {
    id: "usr-104",
    name: "Sophia Martinez",
    email: "smartinez99@yahoo.com",
    status: "ACTIVE",
    accountType: "FREE",
    calculationsCount: 78,
    aiSolvesCount: 12,
    scansCount: 9,
    registeredAt: "2026-04-10T11:45:00.000Z",
    lastActiveAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    devicePlatform: "iOS",
    appVersion: "1.0.3",
  },
];

export const INITIAL_PREMIUM_PURCHASES: PremiumPurchase[] = [
  {
    id: "pur-101",
    userId: "usr-101",
    userName: "David Kim",
    platform: "iOS",
    productId: "solvecalc_premium_lifetime",
    priceUsd: 10.0,
    transactionId: "GPA.3392-8491-1029-88120",
    purchaseDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    status: "VERIFIED",
    receiptVerified: true,
  },
  {
    id: "pur-103",
    userId: "usr-103",
    userName: "Marcus Vance",
    platform: "Android",
    productId: "solvecalc_premium_lifetime",
    priceUsd: 10.0,
    transactionId: "GPA.1102-7744-8891-33290",
    purchaseDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    status: "VERIFIED",
    receiptVerified: true,
  },
  {
    id: "pur-106",
    userId: "usr-106",
    userName: "Lucas Scott",
    platform: "iOS",
    productId: "solvecalc_premium_lifetime",
    priceUsd: 10.0,
    transactionId: "GPA.9912-4411-2091-66512",
    purchaseDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    status: "VERIFIED",
    receiptVerified: true,
  },
  {
    id: "pur-108",
    userId: "usr-108",
    userName: "Nathan Drake",
    platform: "iOS",
    productId: "solvecalc_premium_lifetime",
    priceUsd: 10.0,
    transactionId: "GPA.5521-3312-9901-77810",
    purchaseDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    status: "VERIFIED",
    receiptVerified: true,
  },
];

export const INITIAL_AD_NETWORKS: AdNetworkItem[] = [
  {
    id: "admob",
    name: "Google AdMob (Primary)",
    sdkName: "google_mobile_ads (v5.1.0)",
    priority: 1,
    isEnabled: true,
    appOpenEnabled: true,
    bannerEnabled: true,
    nativeEnabled: false,
    impressionsToday: 18450,
    fillRatePercent: 96.8,
    ecpmUsd: 4.85,
    revenueTodayUsd: 89.48,
    healthStatus: "HEALTHY",
    lastHealthCheck: "Just now",
  },
  {
    id: "network_b",
    name: "Network B (AppLovin MAX)",
    sdkName: "applovin_max (v3.4.1)",
    priority: 2,
    isEnabled: true,
    appOpenEnabled: true,
    bannerEnabled: true,
    nativeEnabled: false,
    impressionsToday: 1420,
    fillRatePercent: 91.2,
    ecpmUsd: 4.12,
    revenueTodayUsd: 5.85,
    healthStatus: "HEALTHY",
    lastHealthCheck: "1 min ago",
  },
  {
    id: "network_c",
    name: "Network C (Unity Ads)",
    sdkName: "unity_ads (v4.3.0)",
    priority: 3,
    isEnabled: true,
    appOpenEnabled: false,
    bannerEnabled: true,
    nativeEnabled: false,
    impressionsToday: 380,
    fillRatePercent: 88.5,
    ecpmUsd: 3.4,
    revenueTodayUsd: 1.29,
    healthStatus: "HEALTHY",
    lastHealthCheck: "2 mins ago",
  },
  {
    id: "house_ad",
    name: "SolveCalc House Ads",
    sdkName: "Built-in Internal Engine",
    priority: 4,
    isEnabled: true,
    appOpenEnabled: true,
    bannerEnabled: true,
    nativeEnabled: true,
    impressionsToday: 840,
    fillRatePercent: 100.0,
    ecpmUsd: 0.0,
    revenueTodayUsd: 0.0,
    healthStatus: "HEALTHY",
    lastHealthCheck: "Just now",
  },
];

export const INITIAL_HOUSE_ADS: HouseAdCampaign[] = [
  {
    id: "house-1",
    title: "Upgrade to SolveCalc Pro — $10 USD",
    description: "Remove all ads forever & unlock all 9 premium calculator themes.",
    ctaText: "GO PRO",
    destination: "paywall",
    isActive: true,
    priority: 1,
    impressions: 12450,
    clicks: 680,
    ctrPercent: 5.46,
    createdAt: "2026-03-01T08:00:00.000Z",
  },
  {
    id: "house-2",
    title: "Retro Casio Scientific Theme Available!",
    description: "Switch to iconic vintage calculator green LCD matrix styling.",
    ctaText: "TRY THEME",
    destination: "themes",
    isActive: true,
    priority: 2,
    impressions: 8900,
    clicks: 410,
    ctrPercent: 4.61,
    createdAt: "2026-04-10T10:30:00.000Z",
  },
  {
    id: "house-3",
    title: "Snap & Solve Any Math Equation",
    description: "Ultra-fast step-by-step camera math recognition with Groq AI.",
    ctaText: "SCAN NOW",
    destination: "scanner",
    isActive: true,
    priority: 3,
    impressions: 6540,
    clicks: 290,
    ctrPercent: 4.43,
    createdAt: "2026-04-20T14:15:00.000Z",
  },
];

export const INITIAL_CONFIG_VERSIONS: RemoteConfigVersion[] = [
  {
    version: "v43 (Current)",
    publishedBy: "Sarah Jenkins (Super Admin)",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    emergencyMode: "NORMAL",
    primaryProvider: "admob",
    fallbackProviders: ["network_b", "network_c", "house_ad"],
    appOpenCooldownMin: 15,
    appOpenMaxPerSession: 1,
    bannerRefreshSec: 30,
    changeSummary: "Adjusted app-open cooldown to 15 minutes for improved UX balance.",
    isActive: true,
  },
  {
    version: "v42",
    publishedBy: "Alex Rivera",
    publishedAt: "2026-05-15T12:00:00.000Z",
    emergencyMode: "NORMAL",
    primaryProvider: "admob",
    fallbackProviders: ["network_b", "network_c", "house_ad"],
    appOpenCooldownMin: 30,
    appOpenMaxPerSession: 1,
    bannerRefreshSec: 30,
    changeSummary: "Added Unity Ads as tertiary fallback provider.",
    isActive: false,
  },
  {
    version: "v41",
    publishedBy: "Sarah Jenkins (Super Admin)",
    publishedAt: "2026-05-01T09:00:00.000Z",
    emergencyMode: "NORMAL",
    primaryProvider: "admob",
    fallbackProviders: ["house_ad"],
    appOpenCooldownMin: 30,
    appOpenMaxPerSession: 1,
    bannerRefreshSec: 45,
    changeSummary: "Initial multi-network remote monetization deployment.",
    isActive: false,
  },
];

export const INITIAL_MONETIZATION_ALERTS: MonetizationAlert[] = [
  {
    id: "alt-01",
    severity: "INFO",
    title: "AdMob Fill Rate Benchmark Met",
    message: "Google AdMob daily fill rate averaged 96.8% across iOS and Android.",
    timestamp: "10 mins ago",
    isResolved: true,
  },
  {
    id: "alt-02",
    severity: "WARNING",
    title: "Network C (Unity) Latency Spike",
    message: "Tertiary fallback network response time reached 1,420ms (Threshold: 1,200ms).",
    providerId: "network_c",
    timestamp: "2 hours ago",
    isResolved: false,
  },
];

export const INITIAL_CALCULATIONS: Calculation[] = [
  {
    id: "calc-1",
    userId: "usr-101",
    userName: "David Kim",
    expression: "sin(30) + cos(60)",
    result: "1",
    mode: "scientific",
    angleMode: "DEG",
    isError: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: "calc-2",
    userId: "usr-103",
    userName: "Marcus Vance",
    expression: "2^10 * sqrt(144)",
    result: "12288",
    mode: "scientific",
    angleMode: "DEG",
    isError: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
];

export const INITIAL_AI_SOLUTIONS: AISolution[] = [
  {
    id: "sol-901",
    userId: "usr-101",
    userName: "David Kim",
    question: "2x + 5 = 15",
    questionType: "Linear Equation",
    finalAnswer: "x = 5",
    solverType: "Groq Llama-3.3 + Deterministic Verifier",
    provider: "Groq Cloud",
    model: "llama-3.3-70b-versatile",
    tokensUsed: 142,
    latencyMs: 380,
    verificationStatus: "VERIFIED",
    status: "COMPLETED",
    steps: [
      {
        stepNumber: 1,
        title: "Subtract 5 from both sides",
        explanation: "2x + 5 - 5 = 15 - 5",
        whyExplanation: "Isolate the variable term on the left side of the equation.",
        equation: "2x = 10",
      },
    ],
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
];

export const INITIAL_SCANS: ScanRecord[] = [
  {
    id: "scn-501",
    userId: "usr-101",
    userName: "David Kim",
    rawOcrText: "2x + 5 = 15",
    finalQuestion: "2x + 5 = 15",
    status: "SUCCESS",
    confidence: 0.99,
    latencyMs: 650,
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
];

export const INITIAL_REPORTS: SolutionReport[] = [
  {
    id: "rep-001",
    solutionId: "sol-902",
    userId: "usr-104",
    userName: "Sophia Martinez",
    question: "x^2 + 5x + 6 = 0",
    answer: "x = -2, x = -3",
    reason: "CONFUSING_EXPLANATION",
    userComment: "The discriminant formula explanation was a bit fast for beginner algebra.",
    status: "PENDING",
    createdAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
  },
];

export const INITIAL_THEMES: ThemeItem[] = [
  {
    id: "white",
    name: "Pure White",
    description: "Crisp, minimalist pure white aesthetic with dark slate typography.",
    primaryColor: "#0F172A",
    secondaryColor: "#F1F5F9",
    backgroundColor: "#FFFFFF",
    surfaceColor: "#F8FAFC",
    numberButtonColor: "#F1F5F9",
    operatorButtonColor: "#E2E8F0",
    isDark: false,
    isActive: true,
    isDefault: false,
    isPremium: false,
    order: 1,
  },
  {
    id: "casio",
    name: "Casio Scientific",
    description: "Iconic classic Casio fx-991EX retro calculator casing with greenish LCD.",
    primaryColor: "#38BDF8",
    secondaryColor: "#262C36",
    backgroundColor: "#1E222A",
    surfaceColor: "#8FA486",
    numberButtonColor: "#ECEFF1",
    operatorButtonColor: "#333A42",
    isDark: true,
    isActive: true,
    isDefault: false,
    isPremium: false,
    order: 2,
  },
  {
    id: "midnight",
    name: "Midnight Blue",
    description: "Deep modern navy blue with sapphire blue accents.",
    primaryColor: "#3B82F6",
    secondaryColor: "#1E293B",
    backgroundColor: "#0F172A",
    surfaceColor: "#1E293B",
    numberButtonColor: "#1E293B",
    operatorButtonColor: "#334155",
    isDark: true,
    isActive: true,
    isDefault: true,
    isPremium: false,
    order: 3,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "✨ New Themes: Pure White & Casio Scientific!",
    message: "Check out the two new themes in Settings to customize your SolveCalc experience.",
    type: "FEATURE",
    targetAudience: "ALL",
    status: "SENT",
    sentAt: "2026-05-01T12:00:00.000Z",
    deliveredCount: 1420,
    openedCount: 980,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud-001",
    adminId: "adm-1",
    adminName: "Sarah Jenkins",
    adminRole: "SUPER_ADMIN",
    action: "PUBLISH_REMOTE_CONFIG",
    resource: "RemoteConfigVersion",
    resourceId: "v43",
    details: "Published remote config v43: App-open cooldown set to 15 mins.",
    ipAddress: "192.168.1.45",
    status: "SUCCESS",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
];

export const INITIAL_AI_PROVIDERS: AIProviderConfig[] = [
  {
    id: "groq-primary",
    name: "Groq Cloud (Ultra-Fast)",
    providerType: "GROQ",
    isPrimary: true,
    isFallback: false,
    isEnabled: true,
    apiKeyMasked: "gsk_••••••••••••••••••••••••••••••••",
    model: "llama-3.3-70b-versatile",
    timeoutMs: 12000,
    maxTokens: 2048,
    dailyLimitUsd: 50.0,
    monthlyLimitUsd: 1200.0,
    currentDaySpendUsd: 4.85,
    currentMonthSpendUsd: 142.3,
  },
];

export const INITIAL_FEATURE_FLAGS: FeatureFlag[] = [
  {
    id: "feat-1",
    key: "AI_SOLVER_ENABLED",
    name: "AI Step-by-Step Solver",
    description: "Enable AI mathematical solving and Learn Mode explanations.",
    isEnabled: true,
    category: "AI",
  },
];

export const INITIAL_SYSTEM_HEALTH: SystemHealthItem[] = [
  {
    name: "SolveCalc Core API",
    status: "ONLINE",
    latencyMs: 124,
    message: "Operating normally (99.98% uptime)",
    lastChecked: "Just now",
  },
  {
    name: "Google AdMob Mediation",
    status: "ONLINE",
    latencyMs: 110,
    message: "AdMob bidding & waterfall health 100%",
    lastChecked: "Just now",
  },
];
